[server]
port = 8501
enableXsrfProtection=true
enableCORS = false
headless=true

[runner]
# Default: true
# fastReruns = false

[client]
# showSidebarNavigation = false

[deprecation]
showPyplotGlobalUse = false
